---
# Test playbook for test_cluster_manager role
# Usage:
#   ansible-playbook test_utils/test_cluster_role.yml -e "action=setup"
#   ansible-playbook test_utils/test_cluster_role.yml -e "action=teardown"

- name: Test cluster manager role
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Validate action parameter
      ansible.builtin.fail:
        msg: "Please provide action parameter: -e 'action=setup' or -e 'action=teardown'"
      when: action is not defined or action not in ['setup', 'teardown']

    - name: Execute cluster manager role
      ansible.builtin.include_role:
        name: test_cluster_manager
      vars:
        cluster_action: "{{ action }}"
