- name: Delete all non-internal zones from Technitium DNS
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../../../tests/integration/integration_config.yml"
  tasks:
    - name: Debug technitium_api_url
      debug:
        var: technitium_api_url
        
    - name: Add record
      technitium_dns_add_record:
        api_url: "{{ technitium_api_url }}"
        api_token: "{{ technitium_api_token }}"
        api_port: "{{ technitium_api_port }}"
        name: "arecord.test-primary.example.com"
        type: "A"
        ipAddress: "192.0.2.1"
        ttl: 3600
      register: add_record

    - name: Get record
      technitium_dns_get_record:
        api_url: "{{ technitium_api_url }}"
        api_token: "{{ technitium_api_token }}"
        api_port: "{{ technitium_api_port }}"
        name: "arecord.test-primary.example.com"
      register: get_record

    - name: Get records
      technitium_dns_get_record:
        api_url: "{{ technitium_api_url }}"
        api_token: "{{ technitium_api_token }}"
        api_port: "{{ technitium_api_port }}"
        name: "test-primary.example.com"
        listZone: true
      register: get_records

    - name: Get zone records
      technitium_dns_get_record:
        api_url: "{{ technitium_api_url }}"
        api_token: "{{ technitium_api_token }}"
        api_port: "{{ technitium_api_port }}"
        name: "test-primary.example.com"
      register: get_zone

    - name: Debug record
      ansible.builtin.debug:
        var: get_record

    - name: Debug record
      ansible.builtin.debug:
        var: get_records

    - name: Debug zone
      ansible.builtin.debug:
        var: get_zone