---
# Ansible Collection release workflow
name: CD

on:
  workflow_run:
    workflows: ["CI"]         # Wait for CI workflow
    branches: [main]          # Only on main branch  
    types: [completed]        # When CI completes
  workflow_dispatch:

# Permissions needed for release-please to create PRs and releases
permissions:
  contents: write
  pull-requests: write

# Default values to simplify job configurations below
env:
  PYTHON_VERSION: '3.12'

jobs:
  release-please:
    runs-on: ubuntu-latest
    # Only run if CI passed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v5
        with:
          # Allow release-please to access older tag information
          fetch-depth: 0
          # Use GITHUB_TOKEN for now, can upgrade to bot later
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Release Please
        id: release_please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json

      - name: Update changelog
        if: ${{ !steps.release_please.outputs.release_created }}
        run: |
          pip install antsibull-changelog --disable-pip-version-check &&\
          git config --global user.name "github-actions[bot]" &&\
          git config --global user.email "github-actions[bot]@users.noreply.github.com" &&\
          git fetch --all &&\
          git checkout release-please--branches--main &&\
          antsibull-changelog release -v --refresh &&\
          git add . &&\
          git commit --amend --no-edit &&\
          git push -f
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  collection-release:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Ansible
        run: |
          pip install ansible --disable-pip-version-check

      - name: Build collection
        run: |
          ansible-galaxy collection build .
          echo "COLLECTION_FILE=$(ls *.tar.gz)" >> $GITHUB_ENV

      - name: Upload collection to Ansible Galaxy
        run: |
          ansible-galaxy collection publish ${{ env.COLLECTION_FILE }} --api-key ${{ secrets.GALAXY_API_KEY }}
          echo "✅ Published to Ansible Galaxy successfully!"

      - name: Upload collection artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-collection-${{ needs.release-please.outputs.tag_name }}
          path: ${{ env.COLLECTION_FILE }}
          retention-days: 90

      - name: Attach collection to GitHub release
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} ${{ env.COLLECTION_FILE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}