---
name: Documentation Only

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

# Required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

env:
  PYTHON_VERSION: '3.12'

jobs:
  # Only run sanity tests to validate documentation
  sanity-docs:
    name: Documentation Sanity Check
    runs-on: ubuntu-latest
    # Only run if commit message starts with "docs:"
    if: startsWith(github.event.head_commit.message, 'docs:')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ansible_collections/effectivelywild/technitium_dns

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install ansible-base (stable-2.19)
      run: pip install https://github.com/ansible/ansible/archive/stable-2.19.tar.gz --disable-pip-version-check

    - name: Install dependencies
      run: pip install -r ./tests/requirements.txt
      working-directory: ansible_collections/effectivelywild/technitium_dns

    - name: Run sanity tests (docs focus)
      run: |
        ansible-test sanity --docker -v --color --test ansible-doc --test validate-modules
      working-directory: ansible_collections/effectivelywild/technitium_dns

  # Generate and deploy documentation
  generate-docs:
    runs-on: ubuntu-latest
    needs: sanity-docs
    # Only run if commit message starts with "docs:"
    if: startsWith(github.event.head_commit.message, 'docs:')
    # Only deploy docs on main branch, but generate for PRs
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Ansible and documentation tools
      run: |
        pip install ansible
        pip install antsibull-docs

    - name: Install collections
      run: |
        # Build and install our collection
        ansible-galaxy collection build . --force
        ansible-galaxy collection install effectivelywild-technitium_dns-*.tar.gz

    - name: Generate documentation
      run: |
        mkdir -p build
        antsibull-docs sphinx-init --use-current --dest-dir ./build effectivelywild.technitium_dns
        cd ./build && pip install -r requirements.txt && ./build.sh

    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4

    - name: Upload documentation artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build/build/html'

    - name: Upload docs as regular artifact (for PRs)
      if: github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: documentation-preview
        path: './build/build/html'
        retention-days: 7

  deploy-docs:
    # Only deploy on main branch pushes AND docs commits
    if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'docs:')
    needs: generate-docs
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4