---
name: Documentation (Release)

on:
  release:
    types: [published]          # Only when a release is published
  workflow_dispatch:            # Keep manual trigger

# Required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generation:
    runs-on: ubuntu-latest
    # Runs on release publish or manual trigger
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Ansible and documentation tools
      run: |
        pip install ansible
        pip install antsibull-docs

    - name: Install collections
      run: |
        # Build and install our collection
        ansible-galaxy collection build . --force
        ansible-galaxy collection install effectivelywild-technitium_dns-*.tar.gz

    - name: Generate documentation
      run: |
        mkdir -p build
        antsibull-docs sphinx-init --use-current --dest-dir ./build effectivelywild.technitium_dns
        cd ./build && pip install -r requirements.txt && ./build.sh

    - name: Inject Google Site Verification Meta Tag
      run: |
        META_TAG='<meta name="google-site-verification" content="${{ secrets.GOOGLE_SITE_VERIFICATION }}" />'
        find ./build/build/html -name "*.html" -exec sed -i "s|</head>|$META_TAG\n</head>|g" {} +

    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4

    - name: Upload documentation artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build/build/html'

    - name: Upload docs as regular artifact (for PRs)
      if: github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: documentation-preview
        path: './build/build/html'
        retention-days: 7

  deploy-docs:
    # Only deploy on main branch pushes
    if: github.ref == 'refs/heads/main'
    needs: generation
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4