---
name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        ansible-version: [">=6.0.0,<7.0.0", ">=7.0.0,<8.0.0"]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "ansible${{ matrix.ansible-version }}"
        pip install requests urllib3

    - name: Build and install collection
      run: |
        ansible-galaxy collection build .
        ansible-galaxy collection install effectivelywild-technitium_dns-*.tar.gz

    - name: Run integration tests
      env:
        TECHNITIUM_API_URL: ${{ secrets.TECHNITIUM_API_URL }}
        TECHNITIUM_API_TOKEN: ${{ secrets.TECHNITIUM_API_TOKEN }}
        TECHNITIUM_API_PORT: ${{ secrets.TECHNITIUM_API_PORT || '5380' }}
        VALIDATE_CERTS: ${{ secrets.VALIDATE_CERTS || 'false' }}
        NOTIFY_NAME_SERVER: ${{ secrets.NOTIFY_NAME_SERVER }}
        DEBUG: ${{ secrets.DEBUG || 'false' }}
      run: |
        cd ~/.ansible/collections/ansible_collections/effectivelywild/technitium_dns
        ansible-playbook -i tests/integration/inventory \
          roles/test_utils/playbooks/run_all_integration_tests.yml -v
      if: ${{ env.TECHNITIUM_API_URL != '' && env.TECHNITIUM_API_TOKEN != '' }}

    - name: Skip integration tests (missing credentials)
      run: |
        echo "::warning::Integration tests skipped - missing required secrets (TECHNITIUM_API_URL, TECHNITIUM_API_TOKEN)"
        echo "To enable integration tests, add the following repository secrets:"
        echo "- TECHNITIUM_API_URL: Your Technitium DNS Server URL"
        echo "- TECHNITIUM_API_TOKEN: Your API authentication token"
        echo "- TECHNITIUM_API_PORT: API port (optional, defaults to 5380)"
        echo "- VALIDATE_CERTS: Certificate validation (optional, defaults to false)"
        echo "- NOTIFY_NAME_SERVER: Notify name server for testing (optional)"
        echo "- DEBUG: Enable debug output (optional, defaults to false)"
      if: ${{ env.TECHNITIUM_API_URL == '' || env.TECHNITIUM_API_TOKEN == '' }}