---
name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Update version in galaxy.yml
      if: github.event_name == 'workflow_dispatch'
      run: |
        sed -i "s/version: .*/version: ${{ github.event.inputs.version }}/" galaxy.yml
        echo "Updated version to ${{ github.event.inputs.version }}"

    - name: Build collection
      run: |
        ansible-galaxy collection build .

    - name: Publish to Ansible Galaxy
      env:
        GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
      run: |
        if [ -n "$GALAXY_API_KEY" ]; then
          ansible-galaxy collection publish *.tar.gz --api-key "$GALAXY_API_KEY"
        else
          echo "::warning::GALAXY_API_KEY not set - skipping Galaxy publish"
          echo "To enable publishing to Galaxy, add GALAXY_API_KEY to repository secrets"
        fi

    - name: Upload collection artifact
      uses: actions/upload-artifact@v3
      with:
        name: collection-tarball
        path: "*.tar.gz"
        retention-days: 30